---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      responses:
        '200':
          description: successful
  "/api/v1/add_category":
    post:
      summary: create category
      responses:
        '200':
          description: successful
  "/api/v1/del_category":
    delete:
      summary: delete category
      responses:
        '200':
          description: successful
tags:
- name: Users
  description: User API endpoint requests
- name: Categories
  description: Category API endpoint requests
- name: Motorcycles
  description: Motorcycle API endpoint requests
- name: Reservations
  description: Reservation API endpoint requests
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
